# EchoForge Agent Configuration
learning_mode: false
llm_model: "gpt-4"
llm_temperature: 0.7
max_conversation_history: 10
confidence_threshold: 0.7
data_dir: "data/echoForge"
logs_dir: "logs"
cache_dir: "cache"
